# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Text as Data
author: Thurston Sexton
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

exclude_patterns:
  - "**.ipynb"

parse:
  myst_enable_extensions:
    - deflist
    - replacements
    - substitution
    - linkify
  myst_substitutions:
    course: PPOL 628
    semester: Spring 2022
    info_panel: |
      - **Section**: {{course}}, Spring 2022 ([Link to Syllabus](syllabus))
      - **Meeting Room/Time**: TBD, 01/12-05/31, Tuesdays (6:30-9:00PM EST)
      - **Course Website**: tlp-coi.github.io/text-data-course

    instructor_panel: |
      - **Name**: Thurston Sexton
      - **Email**: thurston.b.sexton@gmail.com
      - **Twitter**: [@ArchaeoEngineer]()
      - **Github**: [@tbsexton]()

# sphinx options
sphinx:
  config:
    bibtex_reference_style: author_year

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: text-as-data.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/TLP-COI/text-data-course  # Online location of your book
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
