name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    paths:
    - content/**
    - env.yaml
    - env-deploy.yaml

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    # container: ghcr.io/tlp-coi/continuous-scientific-python:master

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: text-data
        environment-file: env-deploy.yaml
    # Install dependencies
    - name: Install dependencies
      run: |
        conda env update --file env.yaml

    # Build the book
    - name: Build the book
      run: |
        jupytext --set-kernel - content/**/*nb.md
        jupyter-book build content/

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./content/_build/html
